-- Tire Survey WebApp
-- Migration 001: initial schema
-- PostgreSQL / Supabase
-- Source of truth for application data model.

create extension if not exists pgcrypto;

create type public.app_role as enum ('supplier','qc_backend','pm_pic','superadmin');
create type public.survey_status as enum (
  'DRAFT',
  'SUBMITTED',
  'QC_REVIEW',
  'QC_REVISION',
  'QC_PASSED',
  'BACKEND_REVIEW',
  'BACKEND_REVISION',
  'COMPLETED',
  'QC_DROPPED'
);
create type public.axle_type as enum ('STEER','DRIVE','FREE_ROLLING');
create type public.tire_configuration as enum ('SINGLE','DOUBLE');
create type public.side_position as enum ('LEFT','RIGHT');
create type public.tire_layer as enum ('SINGLE','INNER','OUTER');
create type public.vehicle_category as enum ('TB','LT');
create type public.segment_type as enum ('BUS','TRUCK');
create type public.bus_category as enum ('INTERCITY_BUS','CITY_BUS');
create type public.truck_category as enum ('GENERAL_CARGO','DUMP_TRUCK','TANKER','TRAILER');
create type public.qc_decision as enum ('PASS','DROP','PENDING');
create type public.photo_review_status as enum ('PASS','REJECT','PENDING');
create type public.backend_status as enum ('PENDING','COMPLETED','REVISION');

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  user_code text unique,
  full_name text not null,
  role public.app_role not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.surveys (
  id uuid primary key default gen_random_uuid(),
  serial_number text unique,
  supplier_id uuid not null references public.users(id),
  survey_date date not null default current_date,
  plate_number text not null,
  province_id bigint,
  city_id bigint,
  vehicle_category public.vehicle_category,
  segment public.segment_type,
  bus_category public.bus_category,
  truck_category public.truck_category,
  specific_vehicle_type text,
  company_name text,
  vehicle_brand_id bigint,
  cargo_type text,
  total_axles integer,
  total_tires integer,
  status public.survey_status not null default 'DRAFT',
  submitted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint surveys_total_axles_nonnegative check (total_axles is null or total_axles >= 0),
  constraint surveys_total_tires_nonnegative check (total_tires is null or total_tires >= 0)
);

-- Master/client-supplied location data
create table public.master_provinces (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.master_cities (
  id bigint generated by default as identity primary key,
  province_id bigint not null references public.master_provinces(id) on delete restrict,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (province_id, name)
);

create table public.master_vehicle_brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.master_tire_brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.master_tire_sizes (
  id bigint generated by default as identity primary key,
  vehicle_category public.vehicle_category not null,
  size text not null,
  ring_size text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (vehicle_category, size)
);

create table public.master_tire_patterns (
  id bigint generated by default as identity primary key,
  vehicle_category public.vehicle_category not null,
  tire_brand_id bigint not null references public.master_tire_brands(id) on delete restrict,
  pattern text not null,
  application text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (vehicle_category, tire_brand_id, pattern)
);

create table public.tire_photo_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  scope text not null check (scope in ('VEHICLE','TIRE')),
  is_required boolean not null default false,
  max_photos integer not null default 10 check (max_photos > 0),
  sort_order integer not null default 0
);

create table public.survey_axle_configs (
  id uuid primary key default gen_random_uuid(),
  survey_id uuid not null references public.surveys(id) on delete cascade,
  axle_order integer not null,
  axle_type public.axle_type not null,
  axle_count integer not null default 1 check (axle_count > 0),
  tire_configuration public.tire_configuration not null,
  tire_count integer not null check (tire_count >= 0),
  created_at timestamptz not null default now(),
  unique (survey_id, axle_type)
);

create table public.survey_tires (
  id uuid primary key default gen_random_uuid(),
  survey_id uuid not null references public.surveys(id) on delete cascade,
  axle_id uuid not null references public.survey_axle_configs(id) on delete cascade,
  axle_type public.axle_type not null,
  axle_number integer not null,
  position_code text not null,
  position_name text not null,
  side public.side_position not null,
  tire_layer public.tire_layer not null,
  tire_sequence integer not null,
  supplier_is_retread boolean,
  backend_brand_id bigint references public.master_tire_brands(id),
  backend_size_id bigint references public.master_tire_sizes(id),
  backend_pattern_id bigint references public.master_tire_patterns(id),
  backend_ply_rating text,
  backend_status public.backend_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (survey_id, position_code)
);

create table public.vehicle_photos (
  id uuid primary key default gen_random_uuid(),
  survey_id uuid not null references public.surveys(id) on delete cascade,
  category_id bigint not null references public.tire_photo_categories(id) on delete restrict,
  storage_path text not null,
  uploaded_by uuid not null references public.users(id),
  created_at timestamptz not null default now()
);

create table public.tire_photos (
  id uuid primary key default gen_random_uuid(),
  survey_tire_id uuid not null references public.survey_tires(id) on delete cascade,
  category_id bigint not null references public.tire_photo_categories(id) on delete restrict,
  storage_path text not null,
  uploaded_by uuid not null references public.users(id),
  created_at timestamptz not null default now()
);

create table public.photo_reviews (
  id uuid primary key default gen_random_uuid(),
  photo_id uuid not null references public.tire_photos(id) on delete cascade,
  reviewer_id uuid not null references public.users(id),
  status public.photo_review_status not null default 'PENDING',
  comment text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.qc_reviews (
  id uuid primary key default gen_random_uuid(),
  survey_id uuid not null references public.surveys(id) on delete cascade,
  reviewer_id uuid not null references public.users(id),
  decision public.qc_decision not null default 'PENDING',
  overall_comment text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.backend_reviews (
  id uuid primary key default gen_random_uuid(),
  survey_id uuid not null references public.surveys(id) on delete cascade,
  reviewer_id uuid not null references public.users(id),
  status public.backend_status not null default 'PENDING',
  comment text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.qc_assignments (
  id uuid primary key default gen_random_uuid(),
  survey_id uuid not null unique references public.surveys(id) on delete cascade,
  assigned_to uuid not null references public.users(id),
  assignment_order bigint not null,
  assigned_at timestamptz not null default now()
);

create table public.serial_counters (
  year integer primary key,
  last_number integer not null default 0 check (last_number >= 0)
);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  survey_id uuid references public.surveys(id) on delete set null,
  actor_id uuid not null references public.users(id),
  action text not null,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

create index idx_surveys_supplier on public.surveys(supplier_id);
create index idx_surveys_status on public.surveys(status);
create index idx_surveys_plate on public.surveys(plate_number);
create index idx_surveys_location on public.surveys(province_id, city_id);
create index idx_survey_axle_configs_survey on public.survey_axle_configs(survey_id);
create index idx_survey_tires_survey on public.survey_tires(survey_id);
create index idx_tire_photos_tire on public.tire_photos(survey_tire_id);
create index idx_photo_reviews_photo on public.photo_reviews(photo_id);
create index idx_activity_logs_survey on public.activity_logs(survey_id);

-- Active plate uniqueness:
-- Same plate can be entered again only after the previous survey is QC_DROPPED.
create unique index uq_active_plate
on public.surveys(plate_number)
where status <> 'QC_DROPPED';

-- Generate official survey SN only when submitting.
create or replace function public.generate_survey_serial()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_year integer := extract(year from now());
  next_number integer;
begin
  insert into public.serial_counters(year, last_number)
  values (current_year, 0)
  on conflict (year) do nothing;

  update public.serial_counters
  set last_number = last_number + 1
  where year = current_year
  returning last_number into next_number;

  return 'SN' || current_year::text || '-' || lpad(next_number::text, 5, '0');
end;
$$;

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger trg_surveys_updated_at
before update on public.surveys
for each row execute function public.set_updated_at();

create trigger trg_survey_tires_updated_at
before update on public.survey_tires
for each row execute function public.set_updated_at();

-- Important: passwords are NOT stored in public.users.
-- Supabase Auth owns credentials.
