-- Migration 002: seed master data from client spreadsheets
-- Source files: KOTA BS COMMERCIAL.xlsx and Data Requirment for Survey (3).xlsx

insert into public.master_provinces(name) values
('Jabodetabek'),
('Banten'),
('Jawa Barat'),
('Jawa Tengah'),
('DIY'),
('Jawa Timur'),
('Bali'),
('Sumatera Selatan'),
('Lampung'),
('Jambi'),
('Bangka Belitung'),
('Bengkulu'),
('Sumatera Barat'),
('Sumatera Utara'),
('Riau'),
('Kalimantan Selatan'),
('Kalimantan Timur'),
('Kalimantan Tengah'),
('Kalimantan Barat'),
('Sulawesi Selatan'),
('sulawesi Utara')
on conflict (name) do nothing;

insert into public.master_cities(province_id,name)
select p.id, x.city
from public.master_provinces p
join (values
('Jabodetabek','Greater Jakarta'),
('Banten','Serang'),
('Banten','Pandeglang'),
('Jawa Barat','Karawang'),
('Jawa Barat','Purwakarta'),
('Jawa Barat','Subang'),
('Jawa Barat','Sumedang'),
('Jawa Barat','Indramayu'),
('Jawa Barat','Majalengka'),
('Jawa Barat','Cirebon'),
('Jawa Barat','Kuningan.'),
('Jawa Barat','Sukabumi'),
('Jawa Barat','Cianjur'),
('Jawa Barat','Bandung'),
('Jawa Barat','Garut'),
('Jawa Barat','Tasikmalaya'),
('Jawa Barat','Ciamis'),
('Jawa Tengah','Brebes'),
('Jawa Tengah','Tegal'),
('Jawa Tengah','Pemalang'),
('Jawa Tengah','Pekalongan'),
('Jawa Tengah','Batang'),
('Jawa Tengah','Kendal'),
('Jawa Tengah','Semarang'),
('Jawa Tengah','Demak'),
('Jawa Tengah','Kudus'),
('Jawa Tengah','Pati'),
('Jawa Tengah','Magelang'),
('Jawa Tengah','Wonosobo'),
('Jawa Tengah','Purworejo'),
('Jawa Tengah','Kebumen'),
('Jawa Tengah','Banyumas'),
('Jawa Tengah','Cilacap'),
('DIY','Yogyakarta'),
('Jawa Timur','Tuban'),
('Jawa Timur','Bojonegoro'),
('Jawa Timur','Lamongan'),
('Jawa Timur','Gresik'),
('Jawa Timur','Surabaya'),
('Jawa Timur','Mojokerto'),
('Jawa Timur','Pasuruan'),
('Jawa Timur','Malang'),
('Jawa Timur','Kediri'),
('Jawa Timur','Nganjuk'),
('Jawa Timur','Madiun'),
('Jawa Timur','Magetan'),
('Jawa Timur','Ngawi.'),
('Bali','Bali.'),
('Sumatera Selatan','Kayu Agung'),
('Sumatera Selatan','Palembang'),
('Sumatera Selatan','Sekayu'),
('Sumatera Selatan','Prabumulih.'),
('Lampung','Bandar Lampung'),
('Lampung','Metro'),
('Lampung','Kota Bumi'),
('Lampung','Kota Agung.'),
('Jambi','Jambi'),
('Jambi','Muaro Jambi'),
('Bangka Belitung','Pangkal Pinang'),
('Bangka Belitung','Sungai Liat.'),
('Bengkulu','Bengkulu'),
('Sumatera Barat','Padang'),
('Sumatera Barat','Padang Pariaman'),
('Sumatera Barat','Padang Panjang'),
('Sumatera Barat','Bukittinggi.'),
('Sumatera Utara','Medan'),
('Sumatera Utara','Binjai'),
('Sumatera Utara','Padang Sidempuan.'),
('Riau','Pekanbaru'),
('Riau','Siak'),
('Riau','Dumai.'),
('Kalimantan Selatan','Banjarmasin'),
('Kalimantan Selatan','Banjar'),
('Kalimantan Selatan','Banjarbaru.'),
('Kalimantan Timur','Balikpapan'),
('Kalimantan Timur','Samarinda'),
('Kalimantan Timur','Penajam'),
('Kalimantan Timur','Kutai.'),
('Kalimantan Tengah','Palangkaraya'),
('Kalimantan Tengah','Sampit'),
('Kalimantan Tengah','Pangkalan Bun.'),
('Kalimantan Barat','Sintang'),
('Kalimantan Barat','Pontianak'),
('Kalimantan Barat','Singkawang.'),
('Sulawesi Selatan','Makassar'),
('Sulawesi Selatan','Maros'),
('Sulawesi Selatan','Gowa.'),
('sulawesi Utara','Manado'),
('sulawesi Utara','Bitung'),
('sulawesi Utara','Minahasa.')
) as x(province_name, city) on p.name=x.province_name
on conflict (province_id,name) do nothing;

insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('FRONT_VIEW','Front View','VEHICLE',true,1,10) on conflict (code) do nothing;
insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('REAR_VIEW','Rear View','VEHICLE',true,2,10) on conflict (code) do nothing;
insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('SIDE_VIEW','Side View','VEHICLE',true,3,10) on conflict (code) do nothing;
insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('SIDEWALL','Sidewall','TIRE',false,10,10) on conflict (code) do nothing;
insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('DOT','DOT','TIRE',false,11,10) on conflict (code) do nothing;
insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('TREAD','Tread','TIRE',false,12,10) on conflict (code) do nothing;
insert into public.tire_photo_categories(code,name,scope,is_required,sort_order,max_photos) values ('ADDITIONAL','Additional','TIRE',false,13,10) on conflict (code) do nothing;

insert into public.master_tire_sizes(vehicle_category,size) values
('TB','10.00-20'),
('TB','10.00R20'),
('TB','11.00-20'),
('TB','11.00R20'),
('TB','11R22.5'),
('TB','12.00-24'),
('TB','12.00R20'),
('TB','12.00R24'),
('TB','225/80R22.5'),
('TB','235/80R22.5'),
('TB','275/70R22.5'),
('TB','295/80R22.5'),
('TB','315/80R22.5'),
('TB','325/95R24'),
('TB','9.00-20'),
('TB','9.00R20'),
('LT','215/75R17.5'),
('LT','235/75R17.5'),
('LT','7.00-14'),
('LT','7.00-16'),
('LT','7.50-14'),
('LT','7.50-15'),
('LT','7.50-16'),
('LT','7.50R15'),
('LT','7.50R16'),
('LT','8.25-16'),
('LT','8.25R16'),
('LT','9.5R17.5')
on conflict (vehicle_category,size) do nothing;

insert into public.master_tire_brands(name) values
('BRAND'),
('GAJAH TUNGGAL'),
('BRIDGESTONE'),
('GOODYEAR'),
('SWALLOW'),
('GITI'),
('AEOLUS'),
('DUNLOP'),
('SAILUN'),
('DURATURN'),
('MRF'),
('TIRON'),
('ASPIRA'),
('JOYALL'),
('NEOLIN'),
('AUSTONE'),
('APOLLO'),
('MICHELIN'),
('CEAT'),
('MAXXIS'),
('WESTLAKE'),
('HIXIH'),
('GOODRIDE'),
('KUNLUN'),
('TBB TIRES'),
('METRO TIRES'),
('ROAD X'),
('DELIUM'),
('GOOD TRIP'),
('CHAO YANG'),
('HANKOOK'),
('BLACK LION'),
('SUPER FLEET'),
('ADVANCE'),
('DRT'),
('AOSEN'),
('VIKRANT'),
('TRAZANO'),
('TECHKING'),
('GAMA TIRES'),
('HENGLI'),
('TRACMAX'),
('EPCO'),
('AULICE'),
('FORTUNE'),
('EVER PROSPER'),
('KAIZEN'),
('DOUBLE STAR'),
('CO PARTNER'),
('MILEVER'),
('WARRIOR'),
('KUMHO'),
('ECED'),
('ASCENDO'),
('JOE PANTHER'),
('GOLDEN CROWN'),
('CST'),
('WIND POWER'),
('ROADLUX'),
('COCREA'),
('KING BRIDGE'),
('RANGER'),
('ROAD ONE'),
('TRIANGLE'),
('QIMA TIRES'),
('SUPER CARGO'),
('OTANI'),
('YARTU'),
('LONG MARCH'),
('WELLRUN'),
('ACHILLES'),
('MAXELL'),
('ROADSHINE'),
('EFFIPLUS'),
('GUANGDA'),
('TRANSMATE'),
('CHILONG'),
('FIRESTONE'),
('DOUBLE COIN'),
('ALTALITE'),
('CHENGSHAN'),
('SUPERWAY'),
('MATIAN'),
('HUAAN'),
('DURUN'),
('KOMBAT'),
('ALLROUND'),
('BF GOODRICH'),
('KINBLI'),
('TRUCKER'),
('BESTANG'),
('O''GREEN'),
('LINGLONG'),
('RUIFULAI'),
('JK TYRE'),
('AMBERSTONE'),
('UNINEST'),
('ROVELO'),
('LEAO'),
('WANLI'),
('GOOD SAFETY'),
('OPARTNER'),
('ANSU'),
('VANLUSTONE'),
('BEFRIEND'),
('LOTOUR TIRE'),
('ATLAS TIRE'),
('SAFEKING'),
('HAWKWAY'),
('DYNA CARGO'),
('HOLDER MASTER'),
('VGLORY'),
('WIN GOOD'),
('BONTYRE'),
('CARLAND'),
('AURUNZE'),
('SUPER NOVA'),
('LIAOLUN'),
('BENCHMARK'),
('WONDERLAND'),
('DESTONE'),
('GOODRICH'),
('HILO'),
('CHANGFENG'),
('GUOXIN'),
('TERCELO'),
('HUBTRAC'),
('DOUPRO'),
('UNITED UT'),
('NAAATS'),
('CACHLAND'),
('HUNG-A'),
('JIANXIN'),
('GREENTOUR'),
('MILEWAY'),
('SPORTRACK'),
('BELSHINA'),
('PIRELLI'),
('HONGTU'),
('FINALIST'),
('ORNET'),
('CONTINENTAL'),
('KASPEN'),
('ANNAITE'),
('KINGSKY'),
('KANER'),
('DMASTER'),
('ROADSTAR')
on conflict (name) do nothing;

insert into public.master_tire_patterns(vehicle_category,tire_brand_id,pattern)
select x.category::public.vehicle_category,b.id,x.pattern
from (values
('LT','GAJAH TUNGGAL','GT LUG PRO'),
('LT','GAJAH TUNGGAL','GT MAX TRACTION'),
('LT','GAJAH TUNGGAL','GT SUPER'),
('LT','GAJAH TUNGGAL','GT SUPER 88'),
('LT','GAJAH TUNGGAL','GT SUPER 88N'),
('LT','GAJAH TUNGGAL','GT SUPER GRIP'),
('LT','GAJAH TUNGGAL','GT TRACTION PRO'),
('LT','BRIDGESTONE','G530'),
('LT','BRIDGESTONE','JSE'),
('LT','BRIDGESTONE','L330'),
('LT','BRIDGESTONE','MRA'),
('LT','BRIDGESTONE','MRD'),
('LT','BRIDGESTONE','MRN'),
('LT','BRIDGESTONE','SMR'),
('LT','BRIDGESTONE','SULPA'),
('LT','BRIDGESTONE','ULS'),
('LT','GOODYEAR','CT147'),
('LT','GOODYEAR','CUSTOM XTRA GRIP'),
('LT','GOODYEAR','CUSTOM XTRA GRIP HD'),
('LT','GOODYEAR','HI-MILER G141'),
('LT','GOODYEAR','HI-MILER S&G'),
('LT','GOODYEAR','HI-MILER S&G HD'),
('LT','GOODYEAR','HMG 2020  HD'),
('LT','GOODYEAR','HMG2020'),
('LT','GOODYEAR','HMG2020 HD'),
('LT','GOODYEAR','OMNITRAC D'),
('LT','GOODYEAR','S200+'),
('LT','GOODYEAR','S501'),
('LT','GOODYEAR','XTRA MILER'),
('LT','SWALLOW','COMBO X LUG'),
('LT','SWALLOW','GRAND V MILLER'),
('LT','SWALLOW','SUPER HD'),
('LT','SWALLOW','SUPER V LUG'),
('LT','SWALLOW','SUPER V8'),
('LT','SWALLOW','SUPER V8 PRO'),
('LT','SWALLOW','SUPER V-LUG'),
('LT','SWALLOW','XTRA MILLER'),
('LT','SWALLOW','X-TREME TRACTION'),
('LT','GITI','GAO822'),
('LT','GITI','GAR820'),
('LT','GITI','GAR890'),
('LT','GITI','GAZ891'),
('LT','GITI','GAZ892'),
('LT','GITI','GAZ893'),
('LT','GITI','GDM607'),
('LT','GITI','GTR955'),
('LT','AEOLUS','ADC09'),
('LT','AEOLUS','AGC08'),
('LT','AEOLUS','AGC23'),
('LT','AEOLUS','ALL ROADS S'),
('LT','AEOLUS','AR535'),
('LT','AEOLUS','ASL67'),
('LT','AEOLUS','ASR11'),
('LT','AEOLUS','ASR24'),
('LT','AEOLUS','ASR30'),
('LT','AEOLUS','ASR35'),
('LT','AEOLUS','HN08'),
('LT','AEOLUS','HN09'),
('LT','AEOLUS','KT867'),
('LT','AEOLUS','NEO ADC99'),
('LT','AEOLUS','NEO ALL ROADS S'),
('LT','AEOLUS','NEO ALL ROADSS'),
('LT','AEOLUS','NEO ALLROAD S'),
('LT','AEOLUS','NEO ALLROADS S'),
('LT','AEOLUS','NEO CONTRUCT 6'),
('LT','AEOLUS','NEO CONTRUCT G'),
('LT','AEOLUS','Y601'),
('LT','DUNLOP','DR2'),
('LT','DUNLOP','SP571'),
('LT','SAILUN','E-CITY'),
('LT','SAILUN','S696'),
('LT','SAILUN','S711'),
('LT','SAILUN','S812'),
('LT','SAILUN','S850'),
('LT','SAILUN','S917'),
('LT','DURATURN','Y226'),
('LT','DURATURN','Y601'),
('LT','DURATURN','Y601+'),
('LT','DURATURN','Y858'),
('LT','DURATURN','Y866'),
('LT','DURATURN','Y868'),
('LT','MRF','M77'),
('LT','MRF','M77R'),
('LT','MRF','SIM4 PLUS'),
('LT','MRF','SLUG XTRA'),
('LT','MRF','SUPER LUG-R'),
('LT','MRF','SUPER MILER'),
('LT','MRF','SUPER MILER 95 R'),
('LT','MRF','SUPER MILER HD'),
('LT','TIRON','FM SUPER HD'),
('LT','TIRON','HF1'),
('LT','TIRON','HFD73 HD'),
('LT','TIRON','HMA 52 HD'),
('LT','TIRON','HMD 53 HD'),
('LT','TIRON','HMD53 HD'),
('LT','TIRON','HS217'),
('LT','TIRON','HS317'),
('LT','TIRON','HS320'),
('LT','TIRON','LONG MILEAGE'),
('LT','TIRON','LUG MASTER'),
('LT','TIRON','SUPER HD'),
('LT','ASPIRA','TB11'),
('LT','ASPIRA','TB12'),
('LT','JOYALL','A515'),
('LT','JOYALL','A605'),
('LT','JOYALL','B875'),
('LT','NEOLIN','M77'),
('LT','NEOLIN','NC51'),
('LT','NEOLIN','NC58'),
('LT','NEOLIN','NM85'),
('LT','NEOLIN','NR16'),
('LT','NEOLIN','NR4'),
('LT','AUSTONE','AT125'),
('LT','AUSTONE','AT126'),
('LT','AUSTONE','AT209'),
('LT','AUSTONE','AT221'),
('LT','AUSTONE','AT27'),
('LT','AUSTONE','AT35'),
('LT','APOLLO','AWR-HD'),
('LT','APOLLO','ENDU TRAX MA2'),
('LT','APOLLO','ENDURACE LD'),
('LT','APOLLO','ENDURACE RA'),
('LT','APOLLO','MILE STAR'),
('LT','APOLLO','MILER STAR'),
('LT','APOLLO','SL HD'),
('LT','MICHELIN','AGILIS HD'),
('LT','MICHELIN','X MULTI'),
('LT','MICHELIN','X MULTI HD'),
('LT','MICHELIN','X MULTI HD Z'),
('LT','MICHELIN','X MULTI Z HD'),
('LT','MICHELIN','XMULTI'),
('LT','MICHELIN','X-MULTI Z HD'),
('LT','MICHELIN','XY23'),
('LT','CEAT','FM SUPER'),
('LT','CEAT','LUG XL'),
('LT','CEAT','LUG XL HD'),
('LT','CEAT','LUG XL+HD'),
('LT','CEAT','LUG XL-HD'),
('LT','CEAT','LUG-XL HD'),
('LT','CEAT','LUG-XLHD'),
('LT','CEAT','MILE SL XL HD'),
('LT','CEAT','MILE XL'),
('LT','CEAT','MILE -XL'),
('LT','CEAT','MILE XL HD'),
('LT','CEAT','MILE XL RIB HD'),
('LT','CEAT','MILE XL SL HD'),
('LT','CEAT','MILER XL SL HD'),
('LT','CEAT','MILE-XL'),
('LT','CEAT','MILE-XL RIB HD'),
('LT','CEAT','MILE-XL RIB+HD'),
('LT','CEAT','MILE-XL SL HD'),
('LT','CEAT','RD818'),
('LT','CEAT','STAMINA'),
('LT','MAXXIS','M276'),
('LT','MAXXIS','UM958'),
('LT','MAXXIS','UM968'),
('LT','MAXXIS','UM968D'),
('LT','WESTLAKE','AZ601'),
('LT','WESTLAKE','CB981'),
('LT','WESTLAKE','CR852'),
('LT','WESTLAKE','CR925'),
('LT','WESTLAKE','CR926'),
('LT','WESTLAKE','R8037'),
('LT','HIXIH','M66A'),
('LT','HIXIH','RA85'),
('LT','GOODRIDE','AZ601'),
('LT','GOODRIDE','CB981'),
('LT','GOODRIDE','CM988'),
('LT','GOODRIDE','CR923'),
('LT','GOODRIDE','CR926'),
('LT','GOODRIDE','EZ330'),
('LT','GOODRIDE','KTX787'),
('LT','GOODRIDE','M8086'),
('LT','GOODRIDE','M80986'),
('LT','GOODRIDE','R8038'),
('LT','KUNLUN','KT225'),
('LT','KUNLUN','KT235'),
('LT','KUNLUN','KT33'),
('LT','KUNLUN','KT588'),
('LT','KUNLUN','KT688'),
('LT','KUNLUN','KT867'),
('LT','TBB TIRES','HR702'),
('LT','TBB TIRES','KTX380'),
('LT','TBB TIRES','KTX733'),
('LT','TBB TIRES','KTX757'),
('LT','TBB TIRES','KTX766'),
('LT','TBB TIRES','KTX767'),
('LT','TBB TIRES','KTX788'),
('LT','TBB TIRES','KTX879'),
('LT','TBB TIRES','MX-306ULTRARIB'),
('LT','METRO TIRES','MT2828'),
('LT','METRO TIRES','SUPER HD'),
('LT','ROAD X','AP865'),
('LT','ROAD X','AP866'),
('LT','ROAD X','DT998'),
('LT','DELIUM','KA353'),
('LT','DELIUM','KR304'),
('LT','DELIUM','STEEL TECHNI KR 304'),
('LT','DELIUM','STEEL TECHNO  KR304'),
('LT','DELIUM','STEEL TECHNO KR304'),
('LT','DELIUM','STEEL TECHNO KR356'),
('LT','GOOD TRIP','KTX733'),
('LT','GOOD TRIP','KTX757'),
('LT','GOOD TRIP','KTX766'),
('LT','GOOD TRIP','KTX767'),
('LT','GOOD TRIP','KTX787'),
('LT','GOOD TRIP','KTX879'),
('LT','GOOD TRIP','R503'),
('LT','GOOD TRIP','R-503'),
('LT','CHAO YANG','AZ697'),
('LT','CHAO YANG','AZ850'),
('LT','CHAO YANG','EZ369'),
('LT','CHAO YANG','R8037'),
('LT','CHAO YANG','R8038'),
('LT','HANKOOK','AH15'),
('LT','HANKOOK','AH35'),
('LT','HANKOOK','AM09'),
('LT','HANKOOK','SMART FLEX AH35'),
('LT','BLACK LION','BLR01'),
('LT','SUPER FLEET','S506'),
('LT','SUPER FLEET','S568'),
('LT','SUPER FLEET','S656'),
('LT','ADVANCE','GL671A'),
('LT','ADVANCE','GL671A+'),
('LT','ADVANCE','GL6720'),
('LT','ADVANCE','GL672D'),
('LT','ADVANCE','GL909A'),
('LT','DRT','KT588'),
('LT','DRT','L139'),
('LT','DRT','LI39'),
('LT','AOSEN','HD616+'),
('LT','AOSEN','LD851'),
('LT','VIKRANT','TRACK KING'),
('LT','VIKRANT','TRACK KING XTRA'),
('LT','VIKRANT','TRACKING'),
('LT','VIKRANT','TRACKING EXTRA'),
('LT','TRAZANO','CB951'),
('LT','TRAZANO','CB981'),
('LT','TECHKING','TKAM S'),
('LT','TECHKING','TKDM5'),
('LT','TECHKING','TKDMS'),
('LT','GAMA TIRES','G631'),
('LT','GAMA TIRES','G655'),
('LT','GAMA TIRES','GT13'),
('LT','HENGLI','DR930'),
('LT','HENGLI','TIBER MAX DR908'),
('LT','TRACMAX','GRT901'),
('LT','EPCO','EP MILER'),
('LT','EPCO','EP MILER BETA'),
('LT','AULICE','AR101'),
('LT','FORTUNE','FT27'),
('LT','EVER PROSPER','EP268'),
('LT','EVER PROSPER','MT1688'),
('LT','KAIZEN','KZ 1005'),
('LT','KAIZEN','KZ-1005'),
('LT','KAIZEN','KZR002'),
('LT','KAIZEN','R002 HD'),
('LT','KAIZEN','R002HD'),
('LT','DOUBLE STAR','DRS008'),
('LT','DOUBLE STAR','DSR008'),
('LT','CO PARTNER','368'),
('LT','CO PARTNER','CP168'),
('LT','CO PARTNER','CP183'),
('LT','CO PARTNER','CP268'),
('LT','MILEVER','SAM 05X'),
('LT','MILEVER','SAM02'),
('LT','MILEVER','SAT06'),
('LT','WARRIOR','WD408'),
('LT','KUMHO','KRS03'),
('LT','ECED','BT926'),
('LT','ASCENDO','AR101'),
('LT','ASCENDO','AR102'),
('LT','ASCENDO','AR102 HD'),
('LT','JOE PANTHER','JPA06'),
('LT','JOE PANTHER','JPA08'),
('LT','GOLDEN CROWN','R8037'),
('LT','CST','CR969 II'),
('LT','WIND POWER','WGC29'),
('LT','WIND POWER','WSR 81'),
('LT','ROADLUX','R519'),
('LT','ROADLUX','R523'),
('LT','COCREA','CR303'),
('LT','COCREA','CR802'),
('LT','KING BRIDGE','KB320'),
('LT','RANGER','L101'),
('LT','RANGER','L323'),
('LT','ROAD ONE','RAB5'),
('LT','TRIANGLE','TR685'),
('LT','QIMA TIRES','XR198'),
('LT','SUPER CARGO','SC318'),
('LT','OTANI','OH 314'),
('LT','OTANI','OH-201'),
('LT','YARTU','AZ69'),
('LT','YARTU','AZ697'),
('LT','LONG MARCH','LM318'),
('LT','LONG MARCH','LM519'),
('LT','WELLRUN','BT360'),
('LT','ACHILLES','HD12'),
('LT','MAXELL','MA338'),
('LT','ROADSHINE','RS602'),
('LT','EFFIPLUS','MOBY R842X'),
('LT','GUANGDA','386'),
('LT','TRANSMATE','TMD18'),
('LT','CHILONG','CA808'),
('TB','BRIDGESTONE','EMLS'),
('TB','BRIDGESTONE','EMSA'),
('TB','BRIDGESTONE','EMSA PREMIUM'),
('TB','BRIDGESTONE','G611'),
('TB','BRIDGESTONE','L317'),
('TB','BRIDGESTONE','L317 EXTRA'),
('TB','BRIDGESTONE','L355'),
('TB','BRIDGESTONE','M840'),
('TB','BRIDGESTONE','M851'),
('TB','BRIDGESTONE','M851 XM'),
('TB','BRIDGESTONE','MRN'),
('TB','BRIDGESTONE','R150'),
('TB','BRIDGESTONE','R150 II'),
('TB','BRIDGESTONE','R151'),
('TB','BRIDGESTONE','R154'),
('TB','BRIDGESTONE','R156'),
('TB','BRIDGESTONE','R172'),
('TB','BRIDGESTONE','SULP'),
('TB','BRIDGESTONE','SUPER U-LUG PREMIUM'),
('TB','BRIDGESTONE','V STEEL MIX 857'),
('TB','BRIDGESTONE','VLGN'),
('TB','BRIDGESTONE','V-LUG'),
('TB','GAJAH TUNGGAL','GT  LUG PRO'),
('TB','GAJAH TUNGGAL','GT  MAX TRACTION'),
('TB','GAJAH TUNGGAL','GT  MILER 88N'),
('TB','GAJAH TUNGGAL','GT  MILER 88N RFD'),
('TB','GAJAH TUNGGAL','GT  MILER RFD'),
('TB','GAJAH TUNGGAL','GT  MILER88N'),
('TB','GAJAH TUNGGAL','GT  MILLER 88N'),
('TB','GAJAH TUNGGAL','GT  MILLER 88N RFD'),
('TB','GAJAH TUNGGAL','GT LUG'),
('TB','GAJAH TUNGGAL','GT LUG PRO'),
('TB','GAJAH TUNGGAL','GT MAC TRACTION'),
('TB','GAJAH TUNGGAL','GT MAX TRACTION'),
('TB','GAJAH TUNGGAL','GT MAXTRACION'),
('TB','GAJAH TUNGGAL','GT MAXTRACTION'),
('TB','GAJAH TUNGGAL','GT MIILER 88N'),
('TB','GAJAH TUNGGAL','GT MILER'),
('TB','GAJAH TUNGGAL','GT MILER 88 RFD'),
('TB','GAJAH TUNGGAL','GT MILER 88N'),
('TB','GAJAH TUNGGAL','GT MILER 88N'),
('TB','GAJAH TUNGGAL','GT MILER 88N HD'),
('TB','GAJAH TUNGGAL','GT MILER 88N RFD'),
('TB','GAJAH TUNGGAL','GT MILER 99'),
('TB','GAJAH TUNGGAL','GT MILER HD'),
('TB','GAJAH TUNGGAL','GT MILER PRO'),
('TB','GAJAH TUNGGAL','GT MILER RFD'),
('TB','GAJAH TUNGGAL','GT MILER88N'),
('TB','GAJAH TUNGGAL','GT MILER88N RFD'),
('TB','GAJAH TUNGGAL','GT MILERN 88N RFD'),
('TB','GAJAH TUNGGAL','GT MILLER 88N'),
('TB','GAJAH TUNGGAL','GT MILLER RFD'),
('TB','GAJAH TUNGGAL','GT MLER RFD'),
('TB','GAJAH TUNGGAL','GT SUPER'),
('TB','GAJAH TUNGGAL','GT SUPER  GRIP'),
('TB','GAJAH TUNGGAL','GT SUPER 88N'),
('TB','GAJAH TUNGGAL','GT SUPER 88N RFD'),
('TB','GAJAH TUNGGAL','GT SUPER GRIP'),
('TB','GAJAH TUNGGAL','GT SUPER RFD'),
('TB','GAJAH TUNGGAL','GT SUPER88N'),
('TB','GAJAH TUNGGAL','GT SUPER88N RFD'),
('TB','GAJAH TUNGGAL','GT. LUG'),
('TB','GAJAH TUNGGAL','GT. MILER 88N'),
('TB','GAJAH TUNGGAL','GT. MILER 88N RFD'),
('TB','GAJAH TUNGGAL','GT. MILER RFD'),
('TB','GAJAH TUNGGAL','GTMILER RFD'),
('TB','GAJAH TUNGGAL','HT MILER RFD'),
('TB','GAJAH TUNGGAL','MILER PRO'),
('TB','GOODYEAR','CB972'),
('TB','GOODYEAR','CM988'),
('TB','GOODYEAR','CR926'),
('TB','GOODYEAR','CR952'),
('TB','GOODYEAR','EMSA'),
('TB','GOODYEAR','G 100'),
('TB','GOODYEAR','GT MILER 88N'),
('TB','GOODYEAR','GT MILER 88N RFD'),
('TB','GOODYEAR','GT MILER RFD'),
('TB','GOODYEAR','GT. MILER RFD'),
('TB','GOODYEAR','HGM 2020'),
('TB','GOODYEAR','HI MILER CT165'),
('TB','GOODYEAR','HI MILER H'),
('TB','GOODYEAR','HI MILER HD'),
('TB','GOODYEAR','HI MILER S&G'),
('TB','GOODYEAR','HI MILER S&G HD'),
('TB','GOODYEAR','HI MILER SG HD'),
('TB','GOODYEAR','HI-MILER S&G'),
('TB','GOODYEAR','HI-MILER S&G HD'),
('TB','GOODYEAR','HM 2020'),
('TB','GOODYEAR','HMF2020 HD'),
('TB','GOODYEAR','HMG  2020'),
('TB','GOODYEAR','HMG  2020  HD'),
('TB','GOODYEAR','HMG  2020 HD'),
('TB','GOODYEAR','HMG 2002'),
('TB','GOODYEAR','HMG 2020'),
('TB','GOODYEAR','HMG 2020  HD'),
('TB','GOODYEAR','HMG 2020 HD'),
('TB','GOODYEAR','HMG 2020 RFD'),
('TB','GOODYEAR','HMG 20202 HD'),
('TB','GOODYEAR','HMG2020'),
('TB','GOODYEAR','HMG2020 HD'),
('TB','GOODYEAR','HMG2020HD'),
('TB','GOODYEAR','K MAX G 667+'),
('TB','GOODYEAR','KIMBER KING'),
('TB','GOODYEAR','KMAX'),
('TB','GOODYEAR','KMAX S'),
('TB','GOODYEAR','KMAX S GEN2'),
('TB','GOODYEAR','R9038'),
('TB','GOODYEAR','ROAD LUG'),
('TB','GOODYEAR','S 200'),
('TB','GOODYEAR','S 200+'),
('TB','GOODYEAR','S 210 K MAX'),
('TB','GOODYEAR','S 210 KMAX'),
('TB','GOODYEAR','S 700'),
('TB','GOODYEAR','S.210 KMAX'),
('TB','GOODYEAR','S200'),
('TB','GOODYEAR','S200+'),
('TB','GOODYEAR','S210 KMAX'),
('TB','GOODYEAR','S210+'),
('TB','GOODYEAR','S210KMAX'),
('TB','GOODYEAR','S700'),
('TB','GOODYEAR','SP343'),
('TB','GOODYEAR','SUPER  ROAD LUG'),
('TB','GOODYEAR','SUPER  ROAD LUG HD'),
('TB','GOODYEAR','SUPER LOAD LUG HD'),
('TB','GOODYEAR','SUPER LOAD LUG X'),
('TB','GOODYEAR','SUPER ROAD LUG'),
('TB','GOODYEAR','SUPER ROAD LUG HD'),
('TB','GOODYEAR','SUPER ROAD LUG X'),
('TB','GOODYEAR','TIMBER KING'),
('TB','GOODYEAR','TIMBER KING KEVLAR'),
('TB','GITI','GAO822'),
('TB','GITI','GAR827'),
('TB','GITI','GAR879'),
('TB','GITI','GAZ 862'),
('TB','GITI','GAZ 891'),
('TB','GITI','GAZ 982'),
('TB','GITI','GAZ827'),
('TB','GITI','GAZ829'),
('TB','GITI','GAZ890'),
('TB','GITI','GAZ891'),
('TB','GITI','GAZ892'),
('TB','GITI','GAZ896'),
('TB','GITI','GDM692'),
('TB','GITI','GSR225'),
('TB','GITI','GT 01'),
('TB','GITI','GT 835'),
('TB','GITI','GT 879'),
('TB','GITI','GT01'),
('TB','GITI','GT668'),
('TB','GITI','GT688'),
('TB','GITI','GZ892'),
('TB','MRF','BA215'),
('TB','MRF','GT MILER RFD'),
('TB','MRF','HS 500'),
('TB','MRF','M729'),
('TB','MRF','M77'),
('TB','MRF','MRF'),
('TB','MRF','MSCLE MILER'),
('TB','MRF','MUCLE MILER'),
('TB','MRF','MUCSLE MILER'),
('TB','MRF','MUSC;LE MILER'),
('TB','MRF','MUSCE MILER'),
('TB','MRF','MUSCLE  MILER'),
('TB','MRF','MUSCLE MIELR'),
('TB','MRF','MUSCLE MIER'),
('TB','MRF','MUSCLE MILER'),
('TB','MRF','MUSCLE MILER R'),
('TB','MRF','MUSCLE MILERD'),
('TB','MRF','MUSCLE MILLER'),
('TB','MRF','MUSCLE MLER'),
('TB','MRF','MUSCLE ROK-X'),
('TB','MRF','MUSCLE ROX'),
('TB','MRF','MUSCLE ROX-X'),
('TB','MRF','MUSCLEMILER'),
('TB','MRF','S3C8'),
('TB','MRF','S3C8 PLUS'),
('TB','MRF','SIM4 PLUS'),
('TB','MRF','STEEL MUSCLE 53C8'),
('TB','MRF','STEEL MUSCLE S1M4'),
('TB','MRF','STEEL MUSCLE S1M4+'),
('TB','MRF','STEEL MUSCLE S3 C8'),
('TB','MRF','SUPER LUG'),
('TB','MRF','SUPER LUG  EXTRA'),
('TB','MRF','SUPER LUG EXTRA'),
('TB','MRF','SUPER LUG FIFTY PLUS'),
('TB','MRF','SUPER MILER'),
('TB','MRF','SUPER MILER HD'),
('TB','MRF','SUPER MILER ID'),
('TB','DURATURN','CR939+'),
('TB','DURATURN','KT 201'),
('TB','DURATURN','KT235'),
('TB','DURATURN','M 800'),
('TB','DURATURN','RM 9'),
('TB','DURATURN','S801'),
('TB','DURATURN','T 139'),
('TB','DURATURN','T139'),
('TB','DURATURN','T233'),
('TB','DURATURN','TI39'),
('TB','DURATURN','Y  601'),
('TB','DURATURN','Y 209'),
('TB','DURATURN','Y 601'),
('TB','DURATURN','Y 601 T'),
('TB','DURATURN','Y 601+'),
('TB','DURATURN','Y 866'),
('TB','DURATURN','Y 866+'),
('TB','DURATURN','Y209'),
('TB','DURATURN','Y601'),
('TB','DURATURN','Y601 +'),
('TB','DURATURN','Y601+'),
('TB','DURATURN','Y610+'),
('TB','DURATURN','Y688+'),
('TB','DURATURN','Y858'),
('TB','DURATURN','Y858+'),
('TB','DURATURN','Y866'),
('TB','DURATURN','Y866+'),
('TB','DURATURN','Y886+'),
('TB','DUNLOP','EMSA'),
('TB','DUNLOP','GINER EXPREES RK90'),
('TB','DUNLOP','GINER EXPRESS RK90'),
('TB','DUNLOP','HI MILER S&G'),
('TB','DUNLOP','LEMK II'),
('TB','DUNLOP','LINER EXPRES'),
('TB','DUNLOP','LINER EXPRES MK II'),
('TB','DUNLOP','LINER EXPRES MKII'),
('TB','DUNLOP','LINER EXPRESS'),
('TB','DUNLOP','LINER EXPRESS MK II'),
('TB','DUNLOP','LINER EXPRESS MKII'),
('TB','DUNLOP','LINER EXPRESS MK-II'),
('TB','DUNLOP','LINER EXPRESS MK-II RK90'),
('TB','DUNLOP','LINER EXPRESS RK90'),
('TB','DUNLOP','LINER EXPRESS RK-90'),
('TB','DUNLOP','M 9'),
('TB','DUNLOP','POWER LUG MASTER'),
('TB','DUNLOP','RM 9'),
('TB','DUNLOP','RM9'),
('TB','DUNLOP','RM98'),
('TB','DUNLOP','SP 320'),
('TB','DUNLOP','SP 343'),
('TB','DUNLOP','SP 571'),
('TB','DUNLOP','SP300'),
('TB','DUNLOP','SP302'),
('TB','DUNLOP','SP320'),
('TB','DUNLOP','SP-320'),
('TB','DUNLOP','SP320+'),
('TB','DUNLOP','SP343'),
('TB','DUNLOP','SP517'),
('TB','DUNLOP','SP521'),
('TB','DUNLOP','SP571'),
('TB','DUNLOP','Y 601+'),
('TB','SAILUN','RA 685'),
('TB','SAILUN','S 606'),
('TB','SAILUN','S 626'),
('TB','SAILUN','S 801'),
('TB','SAILUN','S 811'),
('TB','SAILUN','S 828'),
('TB','SAILUN','S 881'),
('TB','SAILUN','S 917'),
('TB','SAILUN','S606'),
('TB','SAILUN','S626'),
('TB','SAILUN','S801'),
('TB','SAILUN','S811'),
('TB','SAILUN','S8111'),
('TB','SAILUN','S828'),
('TB','SAILUN','S911'),
('TB','SAILUN','S917'),
('TB','HANKOOK','AH11'),
('TB','HANKOOK','AH11K'),
('TB','HANKOOK','AH15'),
('TB','HANKOOK','AH15R'),
('TB','HANKOOK','AH30'),
('TB','HANKOOK','AH31+'),
('TB','HANKOOK','AH31K'),
('TB','HANKOOK','AH51'),
('TB','HANKOOK','AH85'),
('TB','HANKOOK','AM09'),
('TB','HANKOOK','AM81'),
('TB','HANKOOK','DM 80'),
('TB','HANKOOK','DM04'),
('TB','HANKOOK','DM80 D'),
('TB','HANKOOK','SMAR CITY AU06'),
('TB','HANKOOK','SMAR FLEK AH31K'),
('TB','HANKOOK','SMART AH31K'),
('TB','HANKOOK','SMART CITY AU 06'),
('TB','HANKOOK','SMART CITY AU06'),
('TB','HANKOOK','SMART CITY AUDY'),
('TB','HANKOOK','SMART FLEK AH31K'),
('TB','HANKOOK','SMART FLEK AH51'),
('TB','HANKOOK','SMART FLEX  AH31K'),
('TB','HANKOOK','SMART FLEX 31K'),
('TB','HANKOOK','SMART FLEX AH 31+'),
('TB','HANKOOK','SMART FLEX AH 31K'),
('TB','HANKOOK','SMART FLEX AH31+'),
('TB','HANKOOK','SMART FLEX AH31K'),
('TB','HANKOOK','SMART FLEX AH51'),
('TB','HANKOOK','SMART FLEX AH51K'),
('TB','HANKOOK','Y 601+'),
('TB','HIXIH','AH30'),
('TB','HIXIH','ATL V65'),
('TB','HIXIH','BT168'),
('TB','HIXIH','FM78'),
('TB','HIXIH','GA 98'),
('TB','HIXIH','GA98'),
('TB','HIXIH','GAZ 892'),
('TB','HIXIH','H 21F'),
('TB','HIXIH','H 292 F'),
('TB','HIXIH','H 292F'),
('TB','HIXIH','H2 1F'),
('TB','HIXIH','H2 IF'),
('TB','HIXIH','H21F'),
('TB','HIXIH','H292F'),
('TB','HIXIH','H2IF'),
('TB','HIXIH','HD 75'),
('TB','HIXIH','HD75'),
('TB','HIXIH','HN08'),
('TB','HIXIH','HZ IF'),
('TB','HIXIH','HZ1F'),
('TB','HIXIH','HZIF'),
('TB','HIXIH','K 996 A'),
('TB','HIXIH','K996A'),
('TB','HIXIH','K999A'),
('TB','HIXIH','M800 D'),
('TB','HIXIH','M800D'),
('TB','HIXIH','R 95'),
('TB','HIXIH','R95A'),
('TB','HIXIH','RA 05'),
('TB','HIXIH','RA 685'),
('TB','HIXIH','RA 685D'),
('TB','HIXIH','RA 685T'),
('TB','HIXIH','RA 85'),
('TB','HIXIH','RA 865'),
('TB','HIXIH','RA 95'),
('TB','HIXIH','RA05'),
('TB','HIXIH','RA586'),
('TB','HIXIH','RA605'),
('TB','HIXIH','RA685'),
('TB','HIXIH','RA85'),
('TB','HIXIH','RA95'),
('TB','HIXIH','RS85'),
('TB','MICHELIN','KZE 3 R'),
('TB','MICHELIN','KZE 3R'),
('TB','MICHELIN','KZE 5R'),
('TB','MICHELIN','KZE3R'),
('TB','MICHELIN','KZR 3R'),
('TB','MICHELIN','KZY3'),
('TB','MICHELIN','MULTI'),
('TB','MICHELIN','X  MULTI'),
('TB','MICHELIN','X MULTI'),
('TB','MICHELIN','X MULTI HD Z'),
('TB','MICHELIN','X MULTI WAY 3D'),
('TB','MICHELIN','X MUTI'),
('TB','MICHELIN','X WORKS HD'),
('TB','MICHELIN','XJE 4 MIX ENERGY'),
('TB','MICHELIN','XMUL'),
('TB','MICHELIN','XMULTI'),
('TB','MICHELIN','X-MULTI'),
('TB','MICHELIN','XMZ'),
('TB','MICHELIN','XR 43 HD'),
('TB','MICHELIN','XYZ 3HD'),
('TB','MICHELIN','XYZ T3'),
('TB','MICHELIN','XYZ3'),
('TB','MICHELIN','XZE 3R'),
('TB','MICHELIN','XZE2'),
('TB','MICHELIN','XZY 3HD'),
('TB','MICHELIN','XZY3'),
('TB','MICHELIN','XZY3 HD'),
('TB','AEOLUS','ADC09'),
('TB','AEOLUS','AEX1'),
('TB','AEOLUS','AGB20'),
('TB','AEOLUS','AGB21'),
('TB','AEOLUS','AGC08'),
('TB','AEOLUS','AGC23'),
('TB','AEOLUS','AGM10'),
('TB','AEOLUS','ASR 70'),
('TB','AEOLUS','ASR79'),
('TB','AEOLUS','BT168'),
('TB','AEOLUS','GAC23'),
('TB','AEOLUS','GAZ892'),
('TB','AEOLUS','HN 08'),
('TB','AEOLUS','HN08'),
('TB','AEOLUS','HN09'),
('TB','AEOLUS','HN10'),
('TB','AEOLUS','HN257'),
('TB','AEOLUS','K MAX G 667+'),
('TB','AEOLUS','M800D'),
('TB','AEOLUS','NEO AGC 21'),
('TB','AEOLUS','NEO AGC 23'),
('TB','AEOLUS','NEO AGC23'),
('TB','AEOLUS','NEO CONSTRUCT G'),
('TB','AEOLUS','NM86'),
('TB','AEOLUS','Q4'),
('TB','AEOLUS','S 917'),
('TB','SWALLOW','GRAND  V MILER'),
('TB','SWALLOW','GRAND  V MILLER'),
('TB','SWALLOW','GRAND  V88'),
('TB','SWALLOW','GRAND V  MILER'),
('TB','SWALLOW','GRAND V LUG'),
('TB','SWALLOW','GRAND V MILLER'),
('TB','SWALLOW','GRAND V8'),
('TB','SWALLOW','GRAND V88'),
('TB','SWALLOW','GRAND V-LUG'),
('TB','SWALLOW','GRAND VMILER'),
('TB','SWALLOW','GRAND V-MILER'),
('TB','SWALLOW','GRND V88'),
('TB','SWALLOW','GT. MILER RFD'),
('TB','SWALLOW','LINER EXPRESS RK-90'),
('TB','SWALLOW','MUSCLE  MILER'),
('TB','SWALLOW','SUPER HD'),
('TB','SWALLOW','SUPER V8'),
('TB','SWALLOW','SUPER V88'),
('TB','SWALLOW','V88'),
('TB','BLACK LION','BA125'),
('TB','BLACK LION','BA126'),
('TB','BLACK LION','BA152'),
('TB','BLACK LION','BA162'),
('TB','BLACK LION','BA202'),
('TB','BLACK LION','BA215'),
('TB','BLACK LION','BD215'),
('TB','BLACK LION','BD285'),
('TB','BLACK LION','BF188'),
('TB','BLACK LION','BL285'),
('TB','BLACK LION','BL601'),
('TB','BLACK LION','BLG19'),
('TB','BLACK LION','BLH88'),
('TB','BLACK LION','BLM16'),
('TB','BLACK LION','BLR01'),
('TB','BLACK LION','BR162'),
('TB','BLACK LION','BT165'),
('TB','BLACK LION','WD605'),
('TB','GOODRIDE','A9038'),
('TB','GOODRIDE','AS58'),
('TB','GOODRIDE','AS668'),
('TB','GOODRIDE','AS858'),
('TB','GOODRIDE','AZ670'),
('TB','GOODRIDE','AZ686'),
('TB','GOODRIDE','BT168'),
('TB','GOODRIDE','CB905'),
('TB','GOODRIDE','CB919'),
('TB','GOODRIDE','CB926'),
('TB','GOODRIDE','CB972'),
('TB','GOODRIDE','CM193'),
('TB','GOODRIDE','CM333'),
('TB','GOODRIDE','CM913'),
('TB','GOODRIDE','CM926'),
('TB','GOODRIDE','CM958'),
('TB','GOODRIDE','CM988'),
('TB','GOODRIDE','CR 906'),
('TB','GOODRIDE','CR 926'),
('TB','GOODRIDE','CR925'),
('TB','GOODRIDE','CR926'),
('TB','GOODRIDE','CR952'),
('TB','GOODRIDE','CR976A'),
('TB','GOODRIDE','HS 608'),
('TB','GOODRIDE','M9096'),
('TB','GOODRIDE','M9099'),
('TB','GOODRIDE','R 9030'),
('TB','GOODRIDE','R 9038'),
('TB','GOODRIDE','R9036'),
('TB','GOODRIDE','R9038'),
('TB','GOODRIDE','R938'),
('TB','GOODRIDE','ROUTE CONTROL'),
('TB','ECED','B218'),
('TB','ECED','BR168'),
('TB','ECED','BT 218'),
('TB','ECED','BT118'),
('TB','ECED','BT128'),
('TB','ECED','BT168'),
('TB','ECED','BT186'),
('TB','ECED','BT188'),
('TB','ECED','BT218'),
('TB','ECED','BT811'),
('TB','ECED','DT 118'),
('TB','ECED','FM78'),
('TB','ECED','GL 259A'),
('TB','ECED','H2 IF'),
('TB','TIRON','GTM SUPER HD'),
('TB','TIRON','HF5'),
('TB','TIRON','HMA 52'),
('TB','TIRON','HMA51'),
('TB','TIRON','HMA52'),
('TB','TIRON','HS  320'),
('TB','TIRON','HS  500'),
('TB','TIRON','HS 135'),
('TB','TIRON','HS 200'),
('TB','TIRON','HS 315'),
('TB','TIRON','HS 500'),
('TB','TIRON','HS310'),
('TB','TIRON','HS315'),
('TB','TIRON','HS320'),
('TB','TIRON','HS365'),
('TB','TIRON','HS5'),
('TB','TIRON','HS500'),
('TB','TIRON','HS500 SHD'),
('TB','TIRON','HS700'),
('TB','TIRON','LONG MILEAGE'),
('TB','TIRON','LUG MASTER'),
('TB','TIRON','SUPER HD'),
('TB','TIRON','SUPER HDE'),
('TB','CEAT','AR3581'),
('TB','CEAT','CEAT ROCK MAX X3'),
('TB','CEAT','EMSA'),
('TB','CEAT','FM SUPER'),
('TB','CEAT','FM SUPER HD'),
('TB','CEAT','FM SUPER MILE-XL RIB HD'),
('TB','CEAT','FM SUPER XL'),
('TB','CEAT','FM SUPER XL HD'),
('TB','CEAT','FM78'),
('TB','CEAT','FM78 HD'),
('TB','CEAT','HCI SUPER'),
('TB','CEAT','HCL SUPER'),
('TB','CEAT','HCL SUPER HD'),
('TB','CEAT','HCL SUPER HL'),
('TB','CEAT','HCL Super HL HD'),
('TB','CEAT','KM78'),
('TB','CEAT','LUG-XL PRO'),
('TB','CEAT','MI;E XL RIB'),
('TB','CEAT','MILE XL HD'),
('TB','CEAT','MILE XL RIB'),
('TB','CEAT','MILE XL RIB HD'),
('TB','CEAT','MILE XL RIB TRAILER MIXER'),
('TB','CEAT','MILE XL SL'),
('TB','CEAT','MILE XL SL HD'),
('TB','CEAT','MILE XL SL+HD'),
('TB','CEAT','MILER XL+HD'),
('TB','CEAT','MILER-XL RIB+HD'),
('TB','CEAT','MILE-X SL'),
('TB','CEAT','MILE-XL RIB'),
('TB','CEAT','MILE-XL RIB HD'),
('TB','CEAT','MILE-XL SL'),
('TB','CEAT','MINE MAX'),
('TB','CEAT','PRO RIO'),
('TB','CEAT','RD116'),
('TB','CEAT','SUPER HD'),
('TB','CEAT','SUPER XL HD'),
('TB','CEAT','WIN LOAD AW'),
('TB','CEAT','WIN MILE-R'),
('TB','CEAT','WIN SUPER X3'),
('TB','CEAT','WIN SUPER X3D'),
('TB','CEAT','WIN SUPERX3-D'),
('TB','CEAT','WINLOAD AW'),
('TB','CEAT','WINLOAD X5-D'),
('TB','CEAT','WINMILE X3-AW'),
('TB','CEAT','WINMILE-R'),
('TB','CEAT','WINMILER-R'),
('TB','CEAT','WINOAD X5-D'),
('TB','CEAT','XL SL HD'),
('TB','AUSTONE','AR202+'),
('TB','AUSTONE','AT 116A'),
('TB','AUSTONE','AT 202'),
('TB','AUSTONE','AT 202+'),
('TB','AUSTONE','AT 21'),
('TB','AUSTONE','AT 22'),
('TB','AUSTONE','AT 372A'),
('TB','AUSTONE','AT116A'),
('TB','AUSTONE','AT202'),
('TB','AUSTONE','AT202+'),
('TB','AUSTONE','AT27'),
('TB','AUSTONE','AT326'),
('TB','AUSTONE','AT327A'),
('TB','AUSTONE','AT327M'),
('TB','AUSTONE','AT372 A'),
('TB','AUSTONE','AT55 XD'),
('TB','AUSTONE','FT116A'),
('TB','ADVANCE','GL 295A'),
('TB','ADVANCE','GL 622A+'),
('TB','ADVANCE','GL 662  A+'),
('TB','ADVANCE','GL 662 A'),
('TB','ADVANCE','GL 662 A+'),
('TB','ADVANCE','GL 662A'),
('TB','ADVANCE','GL 662A+'),
('TB','ADVANCE','GL 66A2+'),
('TB','ADVANCE','GL 828 A'),
('TB','ADVANCE','GL 99 Z'),
('TB','ADVANCE','GL 99 ZA'),
('TB','ADVANCE','GL 992'),
('TB','ADVANCE','GL 992A'),
('TB','ADVANCE','GL259A'),
('TB','ADVANCE','GL274 A+'),
('TB','ADVANCE','GL274A'),
('TB','ADVANCE','GL292 A'),
('TB','ADVANCE','GL292A'),
('TB','ADVANCE','GL292A II'),
('TB','ADVANCE','GL292AII'),
('TB','ADVANCE','GL622A'),
('TB','ADVANCE','GL622A+'),
('TB','ADVANCE','GL662A'),
('TB','ADVANCE','GL662A+'),
('TB','ADVANCE','GL665A'),
('TB','ADVANCE','GL828A'),
('TB','ADVANCE','GL909A'),
('TB','ADVANCE','GL926'),
('TB','ADVANCE','GL992'),
('TB','ADVANCE','GL992A'),
('TB','ADVANCE','NHS'),
('TB','MAXXIS','DM 938'),
('TB','MAXXIS','M  276 HD'),
('TB','MAXXIS','M 276'),
('TB','MAXXIS','M 276 HD'),
('TB','MAXXIS','M176'),
('TB','MAXXIS','M27'),
('TB','MAXXIS','M27 HD'),
('TB','MAXXIS','M275'),
('TB','MAXXIS','M276'),
('TB','MAXXIS','M276 HD'),
('TB','MAXXIS','M276HD'),
('TB','MAXXIS','M278'),
('TB','MAXXIS','M77'),
('TB','MAXXIS','MAX POWER'),
('TB','MAXXIS','MAX-POWER'),
('TB','MAXXIS','ML 687'),
('TB','MAXXIS','ML687'),
('TB','MAXXIS','MZ76 HD'),
('TB','MAXXIS','UM  938'),
('TB','MAXXIS','UM 938'),
('TB','MAXXIS','UM 958'),
('TB','MAXXIS','UM 968'),
('TB','MAXXIS','UM 985'),
('TB','MAXXIS','UM938'),
('TB','MAXXIS','UM956'),
('TB','MAXXIS','UM958'),
('TB','MAXXIS','UM968'),
('TB','MAXXIS','UM985'),
('TB','MAXXIS','UMD 968'),
('TB','MAXXIS','UR288'),
('TB','MAXXIS','Y 209'),
('TB','KUNLUN','K201'),
('TB','KUNLUN','KT  201'),
('TB','KUNLUN','KT 201'),
('TB','KUNLUN','KT 235'),
('TB','KUNLUN','KT 856+'),
('TB','KUNLUN','KT201'),
('TB','KUNLUN','KT207'),
('TB','KUNLUN','KT235'),
('TB','KUNLUN','KT586'),
('TB','KUNLUN','KT688'),
('TB','KUNLUN','KT856'),
('TB','KUNLUN','KT856+'),
('TB','KUNLUN','KT865'),
('TB','KUNLUN','KT865+'),
('TB','KUNLUN','KT865A'),
('TB','KUNLUN','KT866'),
('TB','KUNLUN','LA88'),
('TB','KUNLUN','T139'),
('TB','FIRESTONE','FD600II'),
('TB','FIRESTONE','FS555'),
('TB','FIRESTONE','FS561'),
('TB','FIRESTONE','FS595'),
('TB','FIRESTONE','UT3000'),
('TB','NEOLIN','AR535'),
('TB','NEOLIN','CONSTRUCT NR12'),
('TB','NEOLIN','KTX879'),
('TB','NEOLIN','NC 51'),
('TB','NEOLIN','NC5'),
('TB','NEOLIN','NC51'),
('TB','NEOLIN','NCSI'),
('TB','NEOLIN','NM 85'),
('TB','NEOLIN','NM08'),
('TB','NEOLIN','NM85'),
('TB','NEOLIN','NM86'),
('TB','NEOLIN','NR 29'),
('TB','NEOLIN','NR28'),
('TB','NEOLIN','NR29'),
('TB','KAIZEN','K 77R'),
('TB','KAIZEN','KA 77Z'),
('TB','KAIZEN','KA77R'),
('TB','KAIZEN','KAZ77R'),
('TB','KAIZEN','KZ 100 S'),
('TB','KAIZEN','KZ 36L+'),
('TB','KAIZEN','KZ 50L HD'),
('TB','KAIZEN','KZ 77 R'),
('TB','KAIZEN','KZ 77R'),
('TB','KAIZEN','KZ-100 S'),
('TB','KAIZEN','KZ1005'),
('TB','KAIZEN','KZ-1005'),
('TB','KAIZEN','KZ100S'),
('TB','KAIZEN','KZ-100S'),
('TB','KAIZEN','KZ-36+'),
('TB','KAIZEN','KZ36L+'),
('TB','KAIZEN','KZ-36L+'),
('TB','KAIZEN','KZ-36L+HD'),
('TB','KAIZEN','KZ-50 HD'),
('TB','KAIZEN','KZ50L'),
('TB','KAIZEN','KZ50L HD'),
('TB','KAIZEN','KZ-50L HD'),
('TB','KAIZEN','KZ-77 R'),
('TB','KAIZEN','KZ77R'),
('TB','KAIZEN','KZ-77R'),
('TB','KAIZEN','KZ7R'),
('TB','KAIZEN','R 001 HD'),
('TB','KAIZEN','R 938'),
('TB','KAIZEN','R001HD'),
('TB','KAIZEN','R001-HD'),
('TB','CST','C307'),
('TB','CST','C8013'),
('TB','CST','C846L'),
('TB','CST','CM988'),
('TB','CST','CR 285'),
('TB','CST','CR 939'),
('TB','CST','CR285'),
('TB','CST','CR393+'),
('TB','CST','CR939+'),
('TB','CST','CST27'),
('TB','CST','GAZ892'),
('TB','DOUBLE COIN','DSR168'),
('TB','DOUBLE COIN','KT 201'),
('TB','DOUBLE COIN','KT 266'),
('TB','DOUBLE COIN','KT 77'),
('TB','DOUBLE COIN','KT266'),
('TB','DOUBLE COIN','KT77'),
('TB','DOUBLE COIN','RB705+'),
('TB','DOUBLE COIN','RBL 800'),
('TB','DOUBLE COIN','RBL11'),
('TB','DOUBLE COIN','RBL450'),
('TB','DOUBLE COIN','RBL800'),
('TB','DOUBLE COIN','RLB 11'),
('TB','DOUBLE COIN','RLB 800'),
('TB','DOUBLE COIN','RLB11'),
('TB','DOUBLE COIN','RLB450'),
('TB','DOUBLE COIN','RLB767'),
('TB','DOUBLE COIN','RLB800'),
('TB','DOUBLE COIN','RLB989'),
('TB','DOUBLE COIN','RM9'),
('TB','DOUBLE COIN','RR 9'),
('TB','DOUBLE COIN','RR705+'),
('TB','DOUBLE COIN','RR9'),
('TB','DOUBLE COIN','TLB989'),
('TB','DOUBLE COIN','WD 989'),
('TB','DOUBLE COIN','WD605'),
('TB','DOUBLE COIN','WD989'),
('TB','ASCENDO','AB635'),
('TB','ASCENDO','AR 890'),
('TB','ASCENDO','AR102'),
('TB','ASCENDO','AR102 HD'),
('TB','ASCENDO','AR3137'),
('TB','ASCENDO','AR525'),
('TB','ASCENDO','AR535'),
('TB','ASCENDO','AR585'),
('TB','ASCENDO','ASCENDO INTERNATIONAL'),
('TB','ASCENDO','R585'),
('TB','ALTALITE','ATL V23'),
('TB','ALTALITE','ATL V65'),
('TB','ALTALITE','ATL V65 RIB LUG'),
('TB','ALTALITE','ATL V65+'),
('TB','ALTALITE','ATL V65+R'),
('TB','ALTALITE','ATL V85'),
('TB','ALTALITE','ATL X28'),
('TB','ALTALITE','MUSCLE MILER'),
('TB','ALTALITE','NM85'),
('TB','ALTALITE','V65'),
('TB','WESTLAKE','CB905'),
('TB','WESTLAKE','CB972'),
('TB','WESTLAKE','CB981'),
('TB','WESTLAKE','CL991'),
('TB','WESTLAKE','CM958'),
('TB','WESTLAKE','CR 926'),
('TB','WESTLAKE','CR922'),
('TB','WESTLAKE','CR925'),
('TB','WESTLAKE','CR926'),
('TB','WESTLAKE','CR952'),
('TB','WESTLAKE','CR9676A'),
('TB','WESTLAKE','CR976A'),
('TB','WESTLAKE','CRS 26'),
('TB','WESTLAKE','CTR926'),
('TB','WESTLAKE','GL911'),
('TB','WESTLAKE','GL969'),
('TB','WESTLAKE','GL991'),
('TB','WESTLAKE','M9088'),
('TB','AOSEN','AGC08'),
('TB','AOSEN','AMA308'),
('TB','AOSEN','HD 616 +'),
('TB','AOSEN','HD 616+'),
('TB','AOSEN','HD616+'),
('TB','AOSEN','MA 771'),
('TB','AOSEN','MA77'),
('TB','AOSEN','MA771'),
('TB','AOSEN','MD761'),
('TB','ROAD X','AP688'),
('TB','ROAD X','AP856'),
('TB','ROAD X','AP865'),
('TB','ROAD X','AP866'),
('TB','ROAD X','AP868'),
('TB','ROAD X','HR621'),
('TB','ROAD X','RH 62'),
('TB','ROAD X','RH 621'),
('TB','ROAD X','RH621'),
('TB','APOLLO','AMAR GOLD'),
('TB','APOLLO','AWR-HD'),
('TB','APOLLO','ENDURACE MA326'),
('TB','APOLLO','ENDURACE MA326+'),
('TB','APOLLO','ENDURACE RA'),
('TB','APOLLO','HAULUG'),
('TB','APOLLO','LOADSTAR SUPER HD'),
('TB','APOLLO','MA326'),
('TB','APOLLO','MINE LUG'),
('TB','APOLLO','MUSCLE  MILER'),
('TB','APOLLO','MUSCLE MILER'),
('TB','APOLLO','SL HD'),
('TB','APOLLO','TXS.2'),
('TB','APOLLO','XPR HD'),
('TB','APOLLO','XPR-HD'),
('TB','APOLLO','XT - 7 HD'),
('TB','APOLLO','XT 7'),
('TB','APOLLO','XT-7'),
('TB','APOLLO','XT-7 HD'),
('TB','APOLLO','XT7HD'),
('TB','FORTUNE','FT 116A'),
('TB','FORTUNE','FT 209'),
('TB','FORTUNE','FT 27'),
('TB','FORTUNE','FT 327'),
('TB','FORTUNE','FT209'),
('TB','FORTUNE','FT27'),
('TB','FORTUNE','FT327'),
('TB','FORTUNE','FT327A'),
('TB','CHENGSHAN','CSP20'),
('TB','CHENGSHAN','CST126'),
('TB','CHENGSHAN','CST206'),
('TB','CHENGSHAN','CST209'),
('TB','CHENGSHAN','CST236'),
('TB','CHENGSHAN','CST27'),
('TB','CHENGSHAN','CST326'),
('TB','CHENGSHAN','CST327'),
('TB','CHENGSHAN','CST327A'),
('TB','CHENGSHAN','M9088'),
('TB','CHENGSHAN','ST206'),
('TB','SUPERWAY','A801'),
('TB','SUPERWAY','AR801'),
('TB','WARRIOR','M540'),
('TB','WARRIOR','M5401'),
('TB','WARRIOR','MS 401'),
('TB','WARRIOR','MS401'),
('TB','WARRIOR','W5401'),
('TB','WARRIOR','WD605'),
('TB','WARRIOR','WS 288'),
('TB','WARRIOR','WS 401'),
('TB','WARRIOR','WS401'),
('TB','TRIANGLE','KT865+'),
('TB','TRIANGLE','TR  668'),
('TB','TRIANGLE','TR  818'),
('TB','TRIANGLE','TR 502'),
('TB','TRIANGLE','TR 618'),
('TB','TRIANGLE','TR 663+'),
('TB','TRIANGLE','TR 668'),
('TB','TRIANGLE','TR 688'),
('TB','TRIANGLE','TR133'),
('TB','TRIANGLE','TR168'),
('TB','TRIANGLE','TR502'),
('TB','TRIANGLE','TR618'),
('TB','TRIANGLE','TR61E'),
('TB','TRIANGLE','TR663'),
('TB','TRIANGLE','TR668'),
('TB','TRIANGLE','TR681'),
('TB','TRIANGLE','TR685'),
('TB','TRIANGLE','TR691'),
('TB','TRIANGLE','TR691E'),
('TB','TRIANGLE','TR69IE'),
('TB','TRIANGLE','TR818'),
('TB','TRIANGLE','TR912'),
('TB','TRIANGLE','TR961E'),
('TB','TRIANGLE','TRC03'),
('TB','MATIAN','HRA 59 H'),
('TB','MATIAN','MT 359'),
('TB','MATIAN','MT359'),
('TB','MATIAN','MT539'),
('TB','MATIAN','MT609'),
('TB','MATIAN','MT689'),
('TB','MATIAN','MY359'),
('TB','WELLRUN','BT 369 N'),
('TB','WELLRUN','BT128'),
('TB','WELLRUN','BT168'),
('TB','WELLRUN','BT369'),
('TB','WELLRUN','GT369N'),
('TB','WELLRUN','T369N'),
('TB','HUAAN','HR A58'),
('TB','HUAAN','HR A59 H'),
('TB','HUAAN','HR A59H'),
('TB','HUAAN','HRA 58'),
('TB','HUAAN','HRA 59 H'),
('TB','HUAAN','HRA 59A'),
('TB','HUAAN','HRA 59H'),
('TB','HUAAN','HRA B59H'),
('TB','HUAAN','HRA S8'),
('TB','HUAAN','HRA58'),
('TB','HUAAN','HRA59'),
('TB','HUAAN','HRA59H'),
('TB','HUAAN','HRAH9'),
('TB','VIKRANT','LOAD XTRA DX'),
('TB','VIKRANT','STAR LUG'),
('TB','VIKRANT','SUPER TRACK KING'),
('TB','VIKRANT','SUPER TRACKKING'),
('TB','VIKRANT','TRACK KING EXTRA DX'),
('TB','VIKRANT','TRACK KING XTRA DX'),
('TB','VIKRANT','TRACK KING XTRA HD'),
('TB','VIKRANT','TRACK MILES DX'),
('TB','VIKRANT','TRACKING EXTRA'),
('TB','VIKRANT','TRACKING XTRA'),
('TB','VIKRANT','TRACKING XTRA DX'),
('TB','VIKRANT','V-ROCK EXTRA'),
('TB','VIKRANT','VTL SUPER'),
('TB','VIKRANT','VTL SUPER DX'),
('TB','DURUN','AL28'),
('TB','DURUN','DH703'),
('TB','DURUN','YTH 3'),
('TB','DURUN','YTH 4'),
('TB','DURUN','YTH3'),
('TB','DURUN','YTH4'),
('TB','DRT','KT 235'),
('TB','DRT','KT 266'),
('TB','DRT','KT201'),
('TB','DRT','KT266'),
('TB','DRT','KT688'),
('TB','DRT','T 711'),
('TB','DRT','T139'),
('TB','DRT','T166'),
('TB','DRT','T223'),
('TB','DRT','T322'),
('TB','DRT','T323'),
('TB','DRT','T711'),
('TB','CHAO YANG','AS858'),
('TB','CHAO YANG','AS868'),
('TB','CHAO YANG','AZ326S'),
('TB','CHAO YANG','AZ850'),
('TB','CHAO YANG','CB332'),
('TB','CHAO YANG','CB972'),
('TB','CHAO YANG','CM998'),
('TB','CHAO YANG','CR 926'),
('TB','CHAO YANG','EZ369'),
('TB','CHAO YANG','GC25A'),
('TB','CHAO YANG','M9088'),
('TB','CHAO YANG','R9037'),
('TB','TRAZANO','AR535'),
('TB','TRAZANO','CR 952'),
('TB','TRAZANO','CR 958'),
('TB','TRAZANO','CR952'),
('TB','TRAZANO','CR958'),
('TB','AULICE','ALL STEEL RADIAL'),
('TB','AULICE','AR101'),
('TB','AULICE','AR101+'),
('TB','AULICE','AR112'),
('TB','AULICE','AR3137'),
('TB','AULICE','AR535'),
('TB','AULICE','HR08'),
('TB','AULICE','HUBEI AULICE TYRE COLTD'),
('TB','DOUBLE STAR','D902'),
('TB','DOUBLE STAR','DFA 100'),
('TB','DOUBLE STAR','DMA105'),
('TB','DOUBLE STAR','DMA108'),
('TB','DOUBLE STAR','DMA108PRO'),
('TB','DOUBLE STAR','DSR A26'),
('TB','DOUBLE STAR','DSR162'),
('TB','DOUBLE STAR','DSR168'),
('TB','DOUBLE STAR','DSRA26'),
('TB','DOUBLE STAR','F10628'),
('TB','DOUBLE STAR','FI0628'),
('TB','DOUBLE STAR','FIO 628'),
('TB','DOUBLE STAR','HP040'),
('TB','DOUBLE STAR','HR169'),
('TB','DOUBLE STAR','M602'),
('TB','QIMA TIRES','AR3137'),
('TB','QIMA TIRES','XR  818'),
('TB','QIMA TIRES','XR 818'),
('TB','QIMA TIRES','XR718'),
('TB','QIMA TIRES','XR818'),
('TB','COCREA','CR 602'),
('TB','COCREA','CR 801D'),
('TB','COCREA','CR 903'),
('TB','COCREA','CR 963'),
('TB','COCREA','CR801HD'),
('TB','COCREA','CR936'),
('TB','COCREA','CR963'),
('TB','ROAD ONE','FS 595 RADIAL'),
('TB','ROAD ONE','GA98'),
('TB','ROAD ONE','QA966'),
('TB','ROAD ONE','QA996'),
('TB','ROAD ONE','RA 685'),
('TB','ROAD ONE','RA 85'),
('TB','ROAD ONE','RA 95'),
('TB','ROAD ONE','RA85'),
('TB','ROAD ONE','RA95'),
('TB','KING BRIDGE','EMSA'),
('TB','KING BRIDGE','KB 526'),
('TB','KING BRIDGE','KB320'),
('TB','KING BRIDGE','KB526'),
('TB','KING BRIDGE','R156'),
('TB','KING BRIDGE','SULP'),
('TB','MILEVER','AP05'),
('TB','MILEVER','BT369'),
('TB','MILEVER','SAH03'),
('TB','MILEVER','SAM 02'),
('TB','MILEVER','SAM01'),
('TB','MILEVER','SAM02'),
('TB','MILEVER','SAP 05'),
('TB','MILEVER','SAP05'),
('TB','MILEVER','STR05'),
('TB','KOMBAT','K200+HD'),
('TB','KOMBAT','K-200+HD'),
('TB','KOMBAT','K-300  HD'),
('TB','KOMBAT','K300 + HD'),
('TB','KOMBAT','K300 HD'),
('TB','KOMBAT','K-300 HD'),
('TB','KOMBAT','K300+ HD'),
('TB','KOMBAT','K300+ HDD'),
('TB','KOMBAT','K300+HD'),
('TB','KOMBAT','K-300+HD'),
('TB','KOMBAT','K300HD'),
('TB','ALLROUND','A602'),
('TB','ALLROUND','AR602'),
('TB','ALLROUND','AR828'),
('TB','BF GOODRICH','CROSS CONTROL'),
('TB','BF GOODRICH','ROUTE CONTROL'),
('TB','KINBLI','AR168'),
('TB','KINBLI','DLS816'),
('TB','KINBLI','DLS816 M+S'),
('TB','KINBLI','DLS816 R1+5'),
('TB','KINBLI','DSL 816 R1+5'),
('TB','KINBLI','KA 202'),
('TB','KINBLI','KF207'),
('TB','TRUCKER','ALL MAKES'),
('TB','TRUCKER','AM311'),
('TB','TRUCKER','AM-VLUG'),
('TB','TRUCKER','SUPER HD'),
('TB','CO PARTNER','CP138'),
('TB','CO PARTNER','CP168'),
('TB','CO PARTNER','CP183'),
('TB','CO PARTNER','CP767'),
('TB','CO PARTNER','CP969'),
('TB','CO PARTNER','CP999G'),
('TB','LONG MARCH','LM120'),
('TB','LONG MARCH','LM216'),
('TB','LONG MARCH','LM268'),
('TB','LONG MARCH','LM306'),
('TB','LONG MARCH','LM308'),
('TB','LONG MARCH','LM309'),
('TB','LONG MARCH','LM903'),
('TB','EVER PROSPER','MT 1688'),
('TB','EVER PROSPER','MT 2828'),
('TB','EVER PROSPER','MT2828'),
('TB','EVER PROSPER','MT3838'),
('TB','EVER PROSPER','MT3883'),
('TB','BESTANG','BST68A'),
('TB','GOOD TRIP','HIGHWAY RIB'),
('TB','GOOD TRIP','HIGHWAY RIB HR706'),
('TB','GOOD TRIP','HR702'),
('TB','GOOD TRIP','HR706'),
('TB','GOOD TRIP','KTX 879'),
('TB','GOOD TRIP','KTX730'),
('TB','GOOD TRIP','KTX733'),
('TB','GOOD TRIP','KTX737'),
('TB','GOOD TRIP','KTX879'),
('TB','GOOD TRIP','RR 706'),
('TB','GOOD TRIP','SUPER SEMI LUG'),
('TB','GOOD TRIP','SUPER SEMI LUG HR702'),
('TB','GOOD TRIP','SUPER SEMILUG HR702'),
('TB','GOOD TRIP','XR358'),
('TB','TECHKING','ETOT'),
('TB','TECHKING','ETRF'),
('TB','TECHKING','TK03'),
('TB','TECHKING','TKAM'),
('TB','TECHKING','TKAM HD'),
('TB','TECHKING','TKAM S'),
('TB','TECHKING','TKAM2'),
('TB','TECHKING','TKAM2S'),
('TB','TECHKING','TKBUS'),
('TB','TECHKING','TKS III'),
('TB','TECHKING','TKTT'),
('TB','JOYALL','A876'),
('TB','JOYALL','A9'),
('TB','JOYALL','TBR12'),
('TB','TBB TIRES','HIGHWAY RIB'),
('TB','TBB TIRES','HR702'),
('TB','TBB TIRES','HR706'),
('TB','TBB TIRES','KT688'),
('TB','TBB TIRES','KTX 688'),
('TB','TBB TIRES','KTX688'),
('TB','TBB TIRES','KTX757'),
('TB','TBB TIRES','KTX766'),
('TB','TBB TIRES','KTX879'),
('TB','TBB TIRES','SUPER SEMILUG'),
('TB','TBB TIRES','XR358'),
('TB','O''GREEN','HL 718'),
('TB','O''GREEN','HL 901'),
('TB','O''GREEN','HL 932'),
('TB','O''GREEN','HL178'),
('TB','O''GREEN','HL718'),
('TB','O''GREEN','HL932'),
('TB','SUPER FLEET','S 303'),
('TB','SUPER FLEET','S 320'),
('TB','SUPER FLEET','S300'),
('TB','SUPER FLEET','S303'),
('TB','SUPER FLEET','S320'),
('TB','SUPER FLEET','S660'),
('TB','SUPER FLEET','S989'),
('TB','OTANI','OH-101'),
('TB','OTANI','OH107'),
('TB','OTANI','OH-107'),
('TB','OTANI','OH-303'),
('TB','OTANI','PERFOMAX'),
('TB','OTANI','PERFORMA X'),
('TB','OTANI','PERFORMAX'),
('TB','OTANI','R707'),
('TB','OTANI','S 808'),
('TB','LINGLONG','LL97'),
('TB','LINGLONG','LLA 08'),
('TB','LINGLONG','RIDE WINGS LFL 185'),
('TB','LINGLONG','STRONG MAX LDO998'),
('TB','RUIFULAI','HF 606'),
('TB','RUIFULAI','HF606'),
('TB','RUIFULAI','HF702N'),
('TB','JK TYRE','JET ACE'),
('TB','JK TYRE','JET POWER 100'),
('TB','JK TYRE','JET POWER 100 HD'),
('TB','JK TYRE','JET POWER 100HD'),
('TB','JK TYRE','JET ROCK XTRA'),
('TB','JK TYRE','JET XTRA LOAD HD'),
('TB','JK TYRE','JET XTRA XLM'),
('TB','JK TYRE','JETWAY JUM'),
('TB','AMBERSTONE','309'),
('TB','AMBERSTONE','366'),
('TB','SUPER CARGO','SC 303'),
('TB','SUPER CARGO','SC 309'),
('TB','SUPER CARGO','SC116'),
('TB','SUPER CARGO','SC303'),
('TB','UNINEST','812N'),
('TB','UNINEST','TIBERON730'),
('TB','UNINEST','TIBERUN 730'),
('TB','UNINEST','TIBERUN 812N'),
('TB','UNINEST','TIBERUN 818'),
('TB','UNINEST','TIBERUN818'),
('TB','ROVELO','SAM3'),
('TB','LEAO','F 816'),
('TB','LEAO','F816'),
('TB','LEAO','LA 08'),
('TB','LEAO','LA08'),
('TB','LEAO','LLD10'),
('TB','WANLI','SAP 05'),
('TB','WANLI','SAP05'),
('TB','GOOD SAFETY','CY768'),
('TB','OPARTNER','CP 183'),
('TB','OPARTNER','CP 813'),
('TB','OPARTNER','CP 9996'),
('TB','OPARTNER','CP168'),
('TB','OPARTNER','CP183'),
('TB','ANSU','BS28'),
('TB','ANSU','BYS98+'),
('TB','VANLUSTONE','AR101'),
('TB','CHILONG','CA808'),
('TB','CHILONG','RA 308'),
('TB','BEFRIEND','BF505'),
('TB','BEFRIEND','BF903'),
('TB','BEFRIEND','GF903'),
('TB','LOTOUR TIRE','LA 218'),
('TB','LOTOUR TIRE','LA 856'),
('TB','LOTOUR TIRE','LF 969'),
('TB','LOTOUR TIRE','LF969'),
('TB','LOTOUR TIRE','MULTI LF 969'),
('TB','YARTU','CB332'),
('TB','YARTU','CB912'),
('TB','YARTU','CR 926'),
('TB','YARTU','CR926'),
('TB','METRO TIRES','LUG MASTER'),
('TB','METRO TIRES','MT3838'),
('TB','ATLAS TIRE','AT08CC'),
('TB','SAFEKING','SK 835 PRO'),
('TB','SAFEKING','SK835PRO'),
('TB','EFFIPLUS','FOLO R129'),
('TB','EFFIPLUS','FOLO R199II'),
('TB','EFFIPLUS','TIGER AM'),
('TB','EFFIPLUS','WOLF DO'),
('TB','EPCO','EP MILER'),
('TB','EPCO','EP MILER LUG'),
('TB','HAWKWAY','HK 701'),
('TB','HAWKWAY','HK701'),
('TB','HAWKWAY','HRA 1'),
('TB','HAWKWAY','HRA1'),
('TB','HAWKWAY','H-RIB V'),
('TB','DYNA CARGO','Y858+'),
('TB','DYNA CARGO','Y866+'),
('TB','DYNA CARGO','Y868+'),
('TB','HOLDER MASTER','M602'),
('TB','HOLDER MASTER','M801D'),
('TB','HOLDER MASTER','M802'),
('TB','HOLDER MASTER','M828'),
('TB','VGLORY','V861'),
('TB','WIN GOOD','HMG  2020  HD'),
('TB','WIN GOOD','WG 128'),
('TB','WIN GOOD','WG118'),
('TB','WIN GOOD','WG128'),
('TB','BONTYRE','BS28'),
('TB','BONTYRE','BT906'),
('TB','BONTYRE','R230'),
('TB','CARLAND','CA802'),
('TB','CARLAND','CA828K'),
('TB','RANGER','T166'),
('TB','AURUNZE','A300'),
('TB','AURUNZE','S6 18 PRO'),
('TB','ROADSHINE','RS610'),
('TB','ROADSHINE','RS617'),
('TB','TRANSMATE','TMD 97'),
('TB','TRANSMATE','TR103'),
('TB','SUPER NOVA','GALAXY V'),
('TB','LIAOLUN','SR 333+'),
('TB','LIAOLUN','SR333+'),
('TB','BENCHMARK','LLA 08'),
('TB','BENCHMARK','LLA08'),
('TB','WONDERLAND','BY06'),
('TB','DESTONE','DHS209'),
('TB','GOODRICH','CR 926'),
('TB','GOODRICH','ROUTE CONTROL'),
('TB','ROADLUX','R268'),
('TB','HILO','309'),
('TB','CHANGFENG','HF 706'),
('TB','CHANGFENG','HF606'),
('TB','GUOXIN','HRA 59'),
('TB','TERCELO','L101'),
('TB','TERCELO','R153'),
('TB','HUBTRAC','MIXED G'),
('TB','HUBTRAC','MIXED G+'),
('TB','DOUPRO','ST869'),
('TB','DOUPRO','ST901'),
('TB','GOLDEN CROWN','CR926'),
('TB','GOLDEN CROWN','R 9037'),
('TB','GOLDEN CROWN','R9037'),
('TB','UNITED UT','STAR LOAD XD'),
('TB','UNITED UT','STAR MILER XD'),
('TB','NAAATS','NA602'),
('TB','CACHLAND','767CAR'),
('TB','HUNG-A','HF5'),
('TB','HENGLI','DR930'),
('TB','JIANXIN','JX359'),
('TB','GREENTOUR','GDM60'),
('TB','MILEWAY','M501'),
('TB','SPORTRACK','BS363'),
('TB','SPORTRACK','SP909'),
('TB','BELSHINA','GEV-114'),
('TB','PIRELLI','FR : 01'),
('TB','HONGTU','HS268'),
('TB','FINALIST','AR168'),
('TB','ORNET','L909'),
('TB','ORNET','S877'),
('TB','MAXELL','SUPER MA1'),
('TB','CONTINENTAL','CONTI RL'),
('TB','KASPEN','HS268'),
('TB','ANNAITE','306'),
('TB','KINGSKY','SK719'),
('TB','KANER','ROOL-HD'),
('TB','DMASTER','DM209'),
('TB','GAMA TIRES','G371'),
('TB','KUMHO','POWER RIB 366'),
('TB','GUANGDA','309'),
('TB','ROADSTAR','R979')
) as x(category,brand_name,pattern)
join public.master_tire_brands b on b.name=x.brand_name
on conflict (vehicle_category,tire_brand_id,pattern) do nothing;

-- NOTE: client master files provide Brand->Pattern by TB/LT and Size by TB/LT separately.
-- Do not implement Pattern filtering by Size until a source mapping is provided.
